### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/journey-to-school#10]
"URL: /nl-NL/projects/journey-to-school

The link to the resources in section "Aanvullende informatie voor docenten" is broken; it should be https://github.com/raspberrypilearning/journey-to-school/tree/master/nl-NL/resources"

**Comment by libxx1** [comment]
Hey @majamanojlovic , I've updated the link in the 'en' page, will this fix the issue for the 'nl-NL' page too? Just wanted to check before I close the issue!

**Comment by majamanojlovic** [comment]
Thanks for cehcking @libxx1! You can close the issue - I'll fix the link in the Dutch translation manually.
