### ISSUE TITLE
Testing feedback

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/journey-to-school#2]
## Step 1
- Additional info for educators in a collapse
## Step 2
- links should open in a new tab
- point out that they should click the Add a Value button. I clicked create and it created my project which I couldn't go back and edit
- should read "picture above" in the penultimate bullet point
## Step 3
- Link to model data should open in new tab
- Link to model data appears broken
- The first task asks them to write some questions for a survey, and tells them it can be anything they like. Wouldn't this step be better earlier? That way they can decide on their values then.
## Step 6
- I think the challenge is too hard at the moment, although maybe experience with other projects might help with this.
- I'd give them some code to get started and then have them adapt it.
![Annotation 2019-06-18 075914](https://user-images.githubusercontent.com/4516338/59659845-0159ca00-919f-11e9-8c45-72fffc0f16f6.png)
## Step 7
Missing

**Comment by daraghbroderick** [comment]
Feedback addressed, thanks.
